[package]
name = "juju-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
display_tree = "1.1.2"
serde_yaml = "0.9.25"
serde = "1"
serde_derive = "1"
home = "0.5.5"